### ISSUE TITLE
Pluggable way to load certificates

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-trust-store#1]
Currently this plugin can load certificates from a local filesystem. However, that's not always possible (think of PaaS environments which discourage local FS use). We should make it possible to load certificates from more sources by implementing a behaviour and configuring the plugin to use it, much like password hashing functions are pluggable in RabbitMQ server as of 3.6.0.

Some examples of alternative stores would be S3-compatible blob stores and services such as [KeyWhiz](https://github.com/square/keywhiz). Supporting those two specifically is not in scope for this issue, by the way.

**Comment by uvzubovs** [comment]
Local file system works. PaaS does not discourage use of local file system, not in Rabbit context. Server SSL certificate, client CA certificate, rabbitmq.config, logs are all sitting on the local file system. 

It would help, though, if the RabbitMQ tile in PCF could accept and upload a client certificate without redeploying and restarting the cluster.

Obtaining certificates from a remote, outside of PCF source, works too and may help with the local file system argument, but it breaks the appliance, all-in-one model of the RabbitMQ tile.

**Comment by michaelklishin** [comment]
@uvzubovs thank you. This feature will be opt-in. Local filesystem will be the default mechanism.

**Comment by michaelklishin** [comment]
#54 introduced a built-in HTTP provider with an example Python app.
