### ISSUE TITLE
Setting Application Environment with Options can Fail on Erlang =< R16B03

### ISSUE THREAD

**Issue by Dzol** [rabbitmq/rabbitmq-trust-store#13]
Passing options along with `application:set_env/4` fails on `R16B03` which is what `dpkg` built Rabbit with for the `3.6.1` Debian package on a Trusty (64).

E.g.:

```Bash
$ erl
Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
```
```Erlang
1> application:set_env(foo, bar, [{baz, brain}]). %% This is okay BUT ...
ok
2> application:set_env(foo, bar, [{alice, wonderland}], [{persistent, true}]). %% ... passing a property-list of options will fail.
** exception error: no function clause matching application:set_env(foo,bar,[{alice,wonderland}],[{persistent,true}]) (application.erl, line 294)
3>
```

The **Trust-Store** does this [here](https://github.com/rabbitmq/rabbitmq-trust-store/blob/master/src/rabbit_trust_store_app.erl#L38).

**Comment by michaelklishin** [comment]
There's already `rabbit_misc:get_env/3` to cover R16B03, we can add a similar `set_env/4` version.

**Comment by Dzol** [comment]
@michaelklishin: Do you mean support a list of options like `timeout` and `persistent` with `rabbit_misc:set_env/4` __if__ the runtime supports them __otherwise__ fail silently?

**Comment by michaelklishin** [comment]
@Dzol I suggest we introduce a compatibility function that delegates to the built-in one of Erlang 17.x/18.x and provides our own implementation (or copies the one in Erlang 18.x) on R16B03.

**Comment by Dzol** [comment]
@michaelklishin: Great: understood.

**Comment by Dzol** [comment]
Having read the implementation in `18.*` I misunderstood exactly what the `persistent` option does. Considering how plugins and applications are started & stopped setting it won't make any difference. But if the functionality is desired then I'll go ahead and implement the compatibility function.

**Comment by michaelklishin** [comment]
@Dzol if it wouldn't make any difference, why implement it?

**Comment by Dzol** [comment]
@michaelklishin: I'll remove the `persistent` option from the call then. In case it'd be helpful elsewhere.

**Comment by michaelklishin** [comment]
@Dzol ok, thanks.
