### ISSUE TITLE
Plugin's boot step assumes an option format which is not compatible with rabbitmq_networking

### ISSUE THREAD

**Issue by Dzol** [rabbitmq/rabbitmq-trust-store#14]
The plugin's [boot-step](https://github.com/rabbitmq/rabbitmq-trust-store/blob/master/src/rabbit_trust_store_app.erl#L66) sets SSL options with OTP's format which looks like:

`{verify_fun, {fun(), term()}}`

But internally, when `rabbit_networking` starts SSL functionality, it expects:

`{Module, Function}` or `{Module, Function, InitialUserState}`

See [1]. So it crashes [here](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_networking.erl#L219) when it calls `module_info/0` on a `fun`.

[1] https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_networking.erl#L197-L200

**Comment by Dzol** [comment]
@michaelklishin: Commit 7456cedc2cb2a3f7fc9378aa31d6e0cf005a6f16 resolves this: release `3.6.1` starts fine on Ubuntu Trusty 64 (Debian package).

But the tests fail because they expect OTP's format for the the `verify_fun` option.

We can rule out calls to `rabbit_trust_store_test:change_configuration/2` and `rabbit_networking:start_ssl_listener/3`, in the test suite, by configuring the broker beforehand with something like the following in the `Makefile`:

```Makefile
WITH_BROKER_TEST_MAKEVARS := \
	RABBITMQ_CONFIG_FILE=$PATH_TO_CONFIGURATION_FOR_TLS_AND_TRUST_STORE
```

Either the repository would have to contain the files for TLS (authority certificate, server certificate, and private key) __or__ invoke a shell script to write them out.

The changes wouldn't be substantial but they may interfere a little with other outstanding issues.

**Comment by michaelklishin** [comment]
@Dzol using a separate config file is certainly OK (and used by some of our test suites). Please submit a PR.

**Comment by michaelklishin** [comment]
@Dzol sorry, was there any progress on this?

**Comment by Dzol** [comment]
Hi Michael,

There's a WIP commit on the branch. I started on it after support & LDAP
tickets yesterday evening but didn't get far. There are notes on the WIP
commit detailing my thoughts... It shouldn't be too much work. But I'm on
holiday until Wednesday.

Joseph.

**Comment by hairyhum** [comment]
Looks like we can just update `rabbit_networking` to support specified format.
