### ISSUE TITLE
Provide a prebuilt ez archive

### ISSUE THREAD

**Issue by agibagib** [rabbitmq/rabbitmq-trust-store#22]
Are you able to make a prebuilt ez archive for those of us who don't have an environment set up for building this plugin from source?

**Comment by michaelklishin** [comment]
We are certainly able to build this plugin but not sure it is ready for prime time yet.

**Comment by michaelklishin** [comment]
Currently the plan is to fix https://github.com/rabbitmq/rabbitmq-trust-store/issues/7 and then do initial release to the Community plugins page.

**Comment by dumbbell** [comment]
Hi!

The plugin is now available for RabbitMQ 3.6.x on the community plugins page:
http://www.rabbitmq.com/community-plugins.html
