### ISSUE TITLE
Log which certs and added or removed

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-trust-store#28]
Would it be possible for audit and general troubleshooting purposes to please log which certs are loaded and/or removed by the plug-in when it starts or refreshes?

**Comment by uvzubovs** [comment]
Thank you for completing this. I see this in the log now:

`=INFO REPORT==== 23-Jun-2016::16:57:27 ===`
`trust store: loading certificate 'trusttest-cert.pem'`

**Comment by kjnilsson** [comment]
@uvzubovs good to hear. Thank you for testing. :)
