### ISSUE TITLE
Include ability to list trusted certs

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-trust-store#31]
Currently, it is possible to see which certs are loaded by the trust store plug-in by executing 

`rabbitmqctl eval 'ets:tab2list(trust_store_whitelist).'`

Can this be improved to show:
- filename (from where the cert was loaded)
- certificate serial number (hex is preferred, but decimal may also be included)
- certificate DN
- certificate issuing CA
- certificate timeframe (issued/expired)

**Comment by michaelklishin** [comment]
Until `rabbitmqctl` gets support for plugin commands we need to provide a function that can produce reasonably friendly output when invoked via `rabbitmqctl eval`.
