### ISSUE TITLE
Obtain certificates from an HTTP endpoint

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-trust-store#37]
I got the wind today from the PCF folks that uploading trusted certs would be very difficult when Rabbit is deployed to PCF. Specifically, adding a trusted cert would require cluster redeployment, given how BOSH works, which is not desirable at all and very risky.

Therefore, I would like to ask you to support an option of retrieving trusted certs from an HTTP endpoint. You may use XKMS standard (https://www.w3.org/TR/xkms) as an example. It discusses the Locate Service, which given cert DN or serial number responds with a list of matching certificates. If you are not into SOAP, you may translate it to REST. 

Thanks!

**Comment by michaelklishin** [comment]
So this is a specific case of #1?

**Comment by uvzubovs** [comment]
Ah, yes. Sorry, I forgot we already discussed this. So, what do you think?

**Comment by michaelklishin** [comment]
We expected this to be a request one day. Should be fairly easy to do.

**Comment by michaelklishin** [comment]
This is a specific case of #1, which someone on the team is investigating. Closing as a duplicate.
