### ISSUE TITLE
File provider: Using directory stats to detect certificate changes is unreliable

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-trust-store#58]
Currently, the file provider uses stat(2) on the certificates directory to detect if certificates were modified in some way (added, updated, removed).

This is unreliable for 2 reasons:

1. The directory modification time is updated when files are added, removed or renamed, but not when a file's content is updated.
1. Even if the underlying filesystem has subsecond time resolution (which is not always the case), the Erlang API doesn't. If a file is added/removed/renamed within the same second after a refresh, the file provider will miss that change.

The latter reason might also be a problem when the file provider uses the file modification time as an ID.

**Comment by dumbbell** [comment]
I believe this issue (more exactly the second reason) is the root cause of the frequent failures we see in CI around the `file_provider_tests:list` testcase:
https://ci-aws.rabbitmq.com/teams/main/pipelines/server-release:v3.7.x/jobs/test-rabbitmq-trust-store/builds/14

**Comment by gerhard** [comment]
Nice find.

**Comment by hairyhum** [comment]
I think that would be ok to skip directory mtime step. 
But we also rely on file modification time to detect that files have changed, which is also 1s resolution.
In real world scenario it should not be an issue, but edge cases can be confusing.
Dropping file mtime check will cause some more file reads and cpu load decoding certificates, but should not be critical once every 30 seconds.

**Comment by dumbbell** [comment]
> Dropping file mtime check will cause some more file reads and cpu load decoding certificates, but should not be critical once every 30 seconds.

It will cause a syscall and thus a context switch, but it's ok to assume that the file metadata will still be in cache if the file was modified at most 30 seconds earlier. So there should be no I/O operations in most cases.
