### ISSUE TITLE
HTTP provider: If-Modified-Since is not up-to-date between certificate changes

### ISSUE THREAD

**Issue by markw83** [rabbitmq/rabbitmq-trust-store#68]
We tried to use RabbitMQ with the rabbitmq-trust-store plugin. We configured the plugin to access an external service which provides the required endpoints.

When the plugin retrieves the list of certificates, the Last-Modified response header is set and the plugin sends the next query with the Last-Modified timestamp in the If-Modified-Since request header. If now something changes on the server, the Last-Modified timestamp is updated in the response header but the plugin still sends requests with the old If-Modified-Since timestamp. Somehow it seems that it is not updated after the first time receiving the Last-Modified timestamp.

Note, we are returning Last-Modified timestamp with 200 OK, if something changed and 304 Not Changed if nothing changed (without Last-Modified timestamp).

**Comment by michaelklishin** [comment]
Do you have an example series of requests and responses to share (feel free to change hostnames and possibly paths)?

**Comment by markw83** [comment]
Hi, here are the requests and responses. Entries with "" are simplified or anonymized. The sequence given of the requests is as they are arriving. The request 5 is only as dummy for pointing out that this request is missing. I found out that it seems that it does not query retrieve new certificates at all after I added the last-modified timestamp. It simply always queries for the list of certificates but not for the certificates itself or updating the timestamp for the query. Please note that for testing it was the same certificate with the same name but simply the server returned a different timestamp. If no timestamp is returned, the plugin alwyas queries every certificate as expected.

REQUEST 1 (first initial request):
----
GET "endpoint" HTTP/1.1
content-length: 0
te: 
host: "ip":"port"
connection: keep-alive

RESPONSE:
----
HTTP/1.1 200 OK
Connection: keep-alive
Last-Modified: Fri, 08 Feb 2019 11:18:48 GMT
X-Powered-By: "data"
Server: "data"
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Feb 2019 06:52:48 GMT

"listofcertificates"



REQUEST 2 (get certificate):
----
GET "endpoint"/"cert" HTTP/1.1
content-length: 0
te: 
host: "ip":"port"
connection: keep-alive

RESPONSE:
----
HTTP/1.1 200 OK
Connection: keep-alive
X-Powered-By: "data"
Server: "data"
Content-Type: text/plain;charset=UTF-8
Content-Length: 1016
Date: Mon, 11 Feb 2019 06:52:48 GMT

"certificate"



REQUEST 3 (nothing changed):
----
GET "endpoint" HTTP/1.1
content-length: 0
te: 
if-modified-since: Fri, 08 Feb 2019 11:18:48 GMT
host: "ip":"port"
connection: keep-alive

RESPONSE:
----
HTTP/1.1 304 Not Modified
X-Powered-By: "data"
Server: "data"
Date: Mon, 11 Feb 2019 06:52:53 GMT



REQUEST 4 (last modified changed):
----
GET "endpoint" HTTP/1.1
content-length: 0
te: 
if-modified-since: Fri, 08 Feb 2019 11:18:48 GMT
host: "ip":"port"
connection: keep-alive

RESPONSE:
----
HTTP/1.1 200 OK
Connection: keep-alive
Last-Modified: Fri, 08 Feb 2019 12:04:48 GMT
X-Powered-By: "data"
Server: "data"
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Feb 2019 06:53:13 GMT

"listofcertificates"



REQUEST 5 (get new certificate):
----
"request not existing instead request 6 is sent"



REQUEST 6 (get certificates):
----
GET "endpoint" HTTP/1.1
content-length: 0
te: 
if-modified-since: Fri, 08 Feb 2019 11:18:48 GMT
host: "ip":"port"
connection: keep-alive

RESPONSE
----
HTTP/1.1 200 OK
Connection: keep-alive
Last-Modified: Fri, 08 Feb 2019 12:04:48 GMT
X-Powered-By: "data"
Server: "data"
Transfer-Encoding: chunked
Content-Type: application/json;charset=UTF-8
Date: Mon, 11 Feb 2019 06:53:18 GMT

"listofcertificates"

**Comment by markw83** [comment]
Do you know already something why the if-modified-since is not updated correctly?

**Comment by lukebakken** [comment]
@markw83 we will try to diagnose this as time allows, thank you.

**Comment by lukebakken** [comment]
@markw83 please see #70
