### ISSUE TITLE
Superfluous error messages when refreshing trust store

### ISSUE THREAD

**Issue by mgrafl** [rabbitmq/rabbitmq-trust-store#75]
Since the fix of #73, the rabbitmq-trust-store plugin spams the log with unnecessary error messages during normal operation: 

> 2020-05-03 03:24:34.773 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:25:04.788 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:25:34.804 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:26:04.821 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:26:34.839 [error] <0.843.0> Trust store will attempt to refresh certificates...
> 2020-05-03 03:27:04.853 [error] <0.843.0> Trust store will attempt to refresh certificates...

These  should be logged at debug level instead.

**Comment by michaelklishin** [comment]
Indeed logging this with error severity was likely a typo and not intentional.
