### ISSUE TITLE
Test suite failures with Erlang 23 on macOS

### ISSUE THREAD

**Issue by pjk25** [rabbitmq/rabbitmq-trust-store#80]
I'm seeing both a test flake and failure that appears to arise from my Erlang and platform combination.

The flake appears to involve `ssl:setops/2` hanging at https://github.com/rabbitmq/rabbitmq-erlang-client/blob/13ab0bcd1cd769f3982deb4690b7e65e7ca3e0ed/src/amqp_main_reader.erl#L58

The failure arises from a slightly different structure of the `tls_alert` error we assert in certain tests - it's now wrapped by a socket error:

```
system_SUITE > http_provider_tests > validate_longer_chain
313
    #1. ***error,
314
            ***case_clause,
315
                 ***error,
316
                     ***socket_error,
317
                          ***tls_alert,
318
                              ***handshake_failure,
319
                                  "TLS client: In state connection received SERVER ALERT: Fatal - Handshake Failure\n"***,
320
                      ***expecting,'connection.start'***,
321
             [***system_SUITE,validate_longer_chain1,1,
322
                  [***file,"test/system_SUITE.erl"***,***line,371***]***]***
323
```

**Comment by pjk25** [comment]
The flake where `ssl:setopts/2` hangs is not strictly limited to cases where the connection should fail, so I'm unsure as to whether or not there is a reasonable fix. The net result currently is that `amqp_connection:start/1` returns `{timeout, _}` so it may be reasonable to catch the timeout so that it returns `{error, {timeout, _}}`.

**Comment by pjk25** [comment]
This post is old, but may be relevant:

http://erlang.2086793.n4.nabble.com/ssl-setopts-hangs-indefinitely-td4692154.html

**Comment by michaelklishin** [comment]
I still see relatively rare (maybe 10% of the time) failures in `validate_longer_chain`:

```
=== Location: [{rabbit_ct_broker_helpers,rpc,1509},
              {system_SUITE,validate_longer_chain,313},
              {test_server,ts_tc,1754},
              {test_server,run_test_case_eval1,1263},
              {test_server,run_test_case_eval,1195}]
=== === Reason: {timeout,{gen_server,call,[<12894.983.0>,connect,60000]}}
```

on Erlang 23 but if this unblocks the Erlang master pipeline, this is already an improvement.

**Comment by pjk25** [comment]
I have added
https://github.com/rabbitmq/rabbitmq-erlang-client/pull/137/commits/fc332bf4e5a5483dee0dc1b77aa64d944cef8020 and https://github.com/rabbitmq/rabbitmq-trust-store/pull/81/commits/ab4ddec21787c37fb3770a28e9a19f7b218816a5 to their respective PRs, which should further reduce the failures in `validate_longer_chain`.

Unfortunately it will probably not eliminate them, as I have occasionally seen `ssl:setopts/2` hang on what should be a successful connection, and I don't believe that we should allow any retries as part of the test itself.

It seems as though `setopts` is more likely to hang on Erlang 23, so maybe there is a regression worth reporting.

**Comment by michaelklishin** [comment]
No failures in 20 runs so far (previously about 20% of runs failed) 👍
